// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package eu.pawelsz.apache.beam.io.protoio;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RawItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoio.RawItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    boolean hasTimestampUsec();
    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    long getTimestampUsec();

    /**
     * <code>optional string device_name = 2;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>optional string device_name = 2;</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>optional string device_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    boolean hasMacAddress();
    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    com.google.protobuf.ByteString getMacAddress();

    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    boolean hasSignalStrength();
    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    int getSignalStrength();
  }
  /**
   * Protobuf type {@code protoio.RawItem}
   */
  public  static final class RawItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoio.RawItem)
      RawItemOrBuilder {
    // Use RawItem.newBuilder() to construct.
    private RawItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RawItem() {
      timestampUsec_ = 0L;
      deviceName_ = "";
      macAddress_ = com.google.protobuf.ByteString.EMPTY;
      signalStrength_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RawItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestampUsec_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              deviceName_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              macAddress_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              signalStrength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_protoio_RawItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_protoio_RawItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.pawelsz.apache.beam.io.protoio.Data.RawItem.class, eu.pawelsz.apache.beam.io.protoio.Data.RawItem.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_USEC_FIELD_NUMBER = 1;
    private long timestampUsec_;
    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    public boolean hasTimestampUsec() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    public long getTimestampUsec() {
      return timestampUsec_;
    }

    public static final int DEVICE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceName_;
    /**
     * <code>optional string device_name = 2;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string device_name = 2;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAC_ADDRESS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString macAddress_;
    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    public boolean hasMacAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    public com.google.protobuf.ByteString getMacAddress() {
      return macAddress_;
    }

    public static final int SIGNAL_STRENGTH_FIELD_NUMBER = 4;
    private int signalStrength_;
    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    public boolean hasSignalStrength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    public int getSignalStrength() {
      return signalStrength_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestampUsec_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, macAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, signalStrength_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestampUsec_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, macAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, signalStrength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof eu.pawelsz.apache.beam.io.protoio.Data.RawItem)) {
        return super.equals(obj);
      }
      eu.pawelsz.apache.beam.io.protoio.Data.RawItem other = (eu.pawelsz.apache.beam.io.protoio.Data.RawItem) obj;

      boolean result = true;
      result = result && (hasTimestampUsec() == other.hasTimestampUsec());
      if (hasTimestampUsec()) {
        result = result && (getTimestampUsec()
            == other.getTimestampUsec());
      }
      result = result && (hasDeviceName() == other.hasDeviceName());
      if (hasDeviceName()) {
        result = result && getDeviceName()
            .equals(other.getDeviceName());
      }
      result = result && (hasMacAddress() == other.hasMacAddress());
      if (hasMacAddress()) {
        result = result && getMacAddress()
            .equals(other.getMacAddress());
      }
      result = result && (hasSignalStrength() == other.hasSignalStrength());
      if (hasSignalStrength()) {
        result = result && (getSignalStrength()
            == other.getSignalStrength());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestampUsec()) {
        hash = (37 * hash) + TIMESTAMP_USEC_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestampUsec());
      }
      if (hasDeviceName()) {
        hash = (37 * hash) + DEVICE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceName().hashCode();
      }
      if (hasMacAddress()) {
        hash = (37 * hash) + MAC_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getMacAddress().hashCode();
      }
      if (hasSignalStrength()) {
        hash = (37 * hash) + SIGNAL_STRENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getSignalStrength();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(eu.pawelsz.apache.beam.io.protoio.Data.RawItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoio.RawItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoio.RawItem)
        eu.pawelsz.apache.beam.io.protoio.Data.RawItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_protoio_RawItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_protoio_RawItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.pawelsz.apache.beam.io.protoio.Data.RawItem.class, eu.pawelsz.apache.beam.io.protoio.Data.RawItem.Builder.class);
      }

      // Construct using eu.pawelsz.apache.beam.io.protoio.Data.RawItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestampUsec_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        macAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        signalStrength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_protoio_RawItem_descriptor;
      }

      public eu.pawelsz.apache.beam.io.protoio.Data.RawItem getDefaultInstanceForType() {
        return eu.pawelsz.apache.beam.io.protoio.Data.RawItem.getDefaultInstance();
      }

      public eu.pawelsz.apache.beam.io.protoio.Data.RawItem build() {
        eu.pawelsz.apache.beam.io.protoio.Data.RawItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.pawelsz.apache.beam.io.protoio.Data.RawItem buildPartial() {
        eu.pawelsz.apache.beam.io.protoio.Data.RawItem result = new eu.pawelsz.apache.beam.io.protoio.Data.RawItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestampUsec_ = timestampUsec_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.macAddress_ = macAddress_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.signalStrength_ = signalStrength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.pawelsz.apache.beam.io.protoio.Data.RawItem) {
          return mergeFrom((eu.pawelsz.apache.beam.io.protoio.Data.RawItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.pawelsz.apache.beam.io.protoio.Data.RawItem other) {
        if (other == eu.pawelsz.apache.beam.io.protoio.Data.RawItem.getDefaultInstance()) return this;
        if (other.hasTimestampUsec()) {
          setTimestampUsec(other.getTimestampUsec());
        }
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000002;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.hasMacAddress()) {
          setMacAddress(other.getMacAddress());
        }
        if (other.hasSignalStrength()) {
          setSignalStrength(other.getSignalStrength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.pawelsz.apache.beam.io.protoio.Data.RawItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.pawelsz.apache.beam.io.protoio.Data.RawItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long timestampUsec_ ;
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public boolean hasTimestampUsec() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public long getTimestampUsec() {
        return timestampUsec_;
      }
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public Builder setTimestampUsec(long value) {
        bitField0_ |= 0x00000001;
        timestampUsec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public Builder clearTimestampUsec() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampUsec_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object deviceName_ = "";
      /**
       * <code>optional string device_name = 2;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString macAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public boolean hasMacAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public com.google.protobuf.ByteString getMacAddress() {
        return macAddress_;
      }
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public Builder setMacAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        macAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public Builder clearMacAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        macAddress_ = getDefaultInstance().getMacAddress();
        onChanged();
        return this;
      }

      private int signalStrength_ ;
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public boolean hasSignalStrength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public int getSignalStrength() {
        return signalStrength_;
      }
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public Builder setSignalStrength(int value) {
        bitField0_ |= 0x00000008;
        signalStrength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public Builder clearSignalStrength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        signalStrength_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoio.RawItem)
    }

    // @@protoc_insertion_point(class_scope:protoio.RawItem)
    private static final eu.pawelsz.apache.beam.io.protoio.Data.RawItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new eu.pawelsz.apache.beam.io.protoio.Data.RawItem();
    }

    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RawItem>
        PARSER = new com.google.protobuf.AbstractParser<RawItem>() {
      public RawItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RawItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RawItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RawItem> getParserForType() {
      return PARSER;
    }

    public eu.pawelsz.apache.beam.io.protoio.Data.RawItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoio_RawItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoio_RawItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\007protoio\"d\n\007RawItem\022\026\n\016time" +
      "stamp_usec\030\001 \001(\003\022\023\n\013device_name\030\002 \001(\t\022\023\n" +
      "\013mac_address\030\003 \001(\014\022\027\n\017signal_strength\030\004 " +
      "\001(\005B#\n!eu.pawelsz.apache.beam.io.protoio"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protoio_RawItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoio_RawItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoio_RawItem_descriptor,
        new java.lang.String[] { "TimestampUsec", "DeviceName", "MacAddress", "SignalStrength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
