// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pl/helloagain/data.proto

package eu.pawelsz.apache.beam.io.protoio;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RawItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 timestamp_usec = 1;
    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    boolean hasTimestampUsec();
    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    long getTimestampUsec();

    // optional string device_name = 2;
    /**
     * <code>optional string device_name = 2;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>optional string device_name = 2;</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>optional string device_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    // optional bytes mac_address = 3;
    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    boolean hasMacAddress();
    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    com.google.protobuf.ByteString getMacAddress();

    // optional int32 signal_strength = 4;
    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    boolean hasSignalStrength();
    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    int getSignalStrength();
  }
  /**
   * Protobuf type {@code helloagain.data.RawItem}
   */
  public static final class RawItem extends
      com.google.protobuf.GeneratedMessage
      implements RawItemOrBuilder {
    // Use RawItem.newBuilder() to construct.
    private RawItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RawItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RawItem defaultInstance;
    public static RawItem getDefaultInstance() {
      return defaultInstance;
    }

    public RawItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RawItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestampUsec_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deviceName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              macAddress_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              signalStrength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_helloagain_data_RawItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_helloagain_data_RawItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.pawelsz.apache.beam.io.protoio.Data.RawItem.class, eu.pawelsz.apache.beam.io.protoio.Data.RawItem.Builder.class);
    }

    public static com.google.protobuf.Parser<RawItem> PARSER =
        new com.google.protobuf.AbstractParser<RawItem>() {
      public RawItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RawItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RawItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 timestamp_usec = 1;
    public static final int TIMESTAMP_USEC_FIELD_NUMBER = 1;
    private long timestampUsec_;
    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    public boolean hasTimestampUsec() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 timestamp_usec = 1;</code>
     */
    public long getTimestampUsec() {
      return timestampUsec_;
    }

    // optional string device_name = 2;
    public static final int DEVICE_NAME_FIELD_NUMBER = 2;
    private java.lang.Object deviceName_;
    /**
     * <code>optional string device_name = 2;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string device_name = 2;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes mac_address = 3;
    public static final int MAC_ADDRESS_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString macAddress_;
    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    public boolean hasMacAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes mac_address = 3;</code>
     */
    public com.google.protobuf.ByteString getMacAddress() {
      return macAddress_;
    }

    // optional int32 signal_strength = 4;
    public static final int SIGNAL_STRENGTH_FIELD_NUMBER = 4;
    private int signalStrength_;
    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    public boolean hasSignalStrength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 signal_strength = 4;</code>
     */
    public int getSignalStrength() {
      return signalStrength_;
    }

    private void initFields() {
      timestampUsec_ = 0L;
      deviceName_ = "";
      macAddress_ = com.google.protobuf.ByteString.EMPTY;
      signalStrength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestampUsec_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, macAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, signalStrength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestampUsec_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, macAddress_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, signalStrength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.pawelsz.apache.beam.io.protoio.Data.RawItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.pawelsz.apache.beam.io.protoio.Data.RawItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code helloagain.data.RawItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.pawelsz.apache.beam.io.protoio.Data.RawItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_helloagain_data_RawItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_helloagain_data_RawItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.pawelsz.apache.beam.io.protoio.Data.RawItem.class, eu.pawelsz.apache.beam.io.protoio.Data.RawItem.Builder.class);
      }

      // Construct using eu.pawelsz.apache.beam.io.protoio.Data.RawItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestampUsec_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        macAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        signalStrength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.pawelsz.apache.beam.io.protoio.Data.internal_static_helloagain_data_RawItem_descriptor;
      }

      public eu.pawelsz.apache.beam.io.protoio.Data.RawItem getDefaultInstanceForType() {
        return eu.pawelsz.apache.beam.io.protoio.Data.RawItem.getDefaultInstance();
      }

      public eu.pawelsz.apache.beam.io.protoio.Data.RawItem build() {
        eu.pawelsz.apache.beam.io.protoio.Data.RawItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.pawelsz.apache.beam.io.protoio.Data.RawItem buildPartial() {
        eu.pawelsz.apache.beam.io.protoio.Data.RawItem result = new eu.pawelsz.apache.beam.io.protoio.Data.RawItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestampUsec_ = timestampUsec_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.macAddress_ = macAddress_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.signalStrength_ = signalStrength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.pawelsz.apache.beam.io.protoio.Data.RawItem) {
          return mergeFrom((eu.pawelsz.apache.beam.io.protoio.Data.RawItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.pawelsz.apache.beam.io.protoio.Data.RawItem other) {
        if (other == eu.pawelsz.apache.beam.io.protoio.Data.RawItem.getDefaultInstance()) return this;
        if (other.hasTimestampUsec()) {
          setTimestampUsec(other.getTimestampUsec());
        }
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000002;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.hasMacAddress()) {
          setMacAddress(other.getMacAddress());
        }
        if (other.hasSignalStrength()) {
          setSignalStrength(other.getSignalStrength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.pawelsz.apache.beam.io.protoio.Data.RawItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.pawelsz.apache.beam.io.protoio.Data.RawItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 timestamp_usec = 1;
      private long timestampUsec_ ;
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public boolean hasTimestampUsec() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public long getTimestampUsec() {
        return timestampUsec_;
      }
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public Builder setTimestampUsec(long value) {
        bitField0_ |= 0x00000001;
        timestampUsec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp_usec = 1;</code>
       */
      public Builder clearTimestampUsec() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampUsec_ = 0L;
        onChanged();
        return this;
      }

      // optional string device_name = 2;
      private java.lang.Object deviceName_ = "";
      /**
       * <code>optional string device_name = 2;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 2;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceName_ = value;
        onChanged();
        return this;
      }

      // optional bytes mac_address = 3;
      private com.google.protobuf.ByteString macAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public boolean hasMacAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public com.google.protobuf.ByteString getMacAddress() {
        return macAddress_;
      }
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public Builder setMacAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        macAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes mac_address = 3;</code>
       */
      public Builder clearMacAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        macAddress_ = getDefaultInstance().getMacAddress();
        onChanged();
        return this;
      }

      // optional int32 signal_strength = 4;
      private int signalStrength_ ;
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public boolean hasSignalStrength() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public int getSignalStrength() {
        return signalStrength_;
      }
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public Builder setSignalStrength(int value) {
        bitField0_ |= 0x00000008;
        signalStrength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 signal_strength = 4;</code>
       */
      public Builder clearSignalStrength() {
        bitField0_ = (bitField0_ & ~0x00000008);
        signalStrength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:helloagain.data.RawItem)
    }

    static {
      defaultInstance = new RawItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:helloagain.data.RawItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_helloagain_data_RawItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_helloagain_data_RawItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030pl/helloagain/data.proto\022\017helloagain.d" +
      "ata\"d\n\007RawItem\022\026\n\016timestamp_usec\030\001 \001(\003\022\023" +
      "\n\013device_name\030\002 \001(\t\022\023\n\013mac_address\030\003 \001(\014" +
      "\022\027\n\017signal_strength\030\004 \001(\005\"e\n\004Item\022\026\n\016tim" +
      "estamp_usec\030\001 \001(\003\022\023\n\013location_id\030\002 \001(\005\022\023" +
      "\n\013mac_address\030\003 \001(\014\022\033\n\023signal_strength_d" +
      "Bm\030\004 \001(\005\"S\n\017LocationMacHour\022\023\n\013location_" +
      "id\030\001 \001(\005\022\023\n\013mac_address\030\002 \001(\014\022\026\n\016timesta" +
      "mp_usec\030\003 \001(\003\"Z\n\rDeviceMacHour\022\023\n\013device" +
      "_name\030\001 \001(\t\022\023\n\013mac_address\030\002 \001(\014\022\037\n\027date",
      "hour_timestamp_usec\030\003 \001(\003\"K\n\020DailyMacTyp" +
      "eStat\022\026\n\016timestamp_usec\030\001 \001(\003\022\020\n\010mac_typ" +
      "e\030\003 \001(\005\022\r\n\005count\030\004 \001(\003\"s\n\026DailyReqDevice" +
      "TypeStat\022\026\n\016timestamp_usec\030\001 \001(\003\022\023\n\013devi" +
      "ce_name\030\002 \001(\t\022\020\n\010mac_type\030\003 \001(\005\022\014\n\004macs\030" +
      "\004 \001(\003\022\014\n\004reqs\030\005 \001(\003\"g\n\023ActiveMacDeviceSt" +
      "at\022\023\n\013device_name\030\001 \001(\t\022\023\n\013mac_address\030\002" +
      " \001(\014\022\022\n\ndev_active\030\003 \001(\005\022\022\n\nmac_active\030\004" +
      " \001(\005\"\212\001\n\025ActiveMacLocationStat\022\023\n\013locati" +
      "on_id\030\001 \001(\005\022\037\n\027location_request_number\030\005",
      " \001(\003\022\023\n\013mac_address\030\002 \001(\014\022\022\n\ndev_active\030" +
      "\003 \001(\005\022\022\n\nmac_active\030\004 \001(\005\"\214\001\n\027MacSignalI" +
      "nLocationStat\022\023\n\013location_id\030\001 \001(\005\022\023\n\013ma" +
      "c_address\030\002 \001(\014\022\023\n\013signal_mean\030\003 \001(\001\022\032\n\022" +
      "standard_deviation\030\004 \001(\001\022\026\n\016request_numb" +
      "er\030\006 \001(\003\"\315\001\n\017LocationMacStat\022\023\n\013location" +
      "_id\030\001 \001(\005\022\023\n\013mac_address\030\002 \001(\014\022\022\n\ndev_ac" +
      "tive\030\003 \001(\005\022\022\n\nmac_active\030\004 \001(\005\022\023\n\013signal" +
      "_mean\030\005 \001(\001\022\032\n\022standard_deviation\030\006 \001(\001\022" +
      "\026\n\016request_number\030\007 \001(\003\022\037\n\027location_requ",
      "est_number\030\010 \001(\003\"\207\002\n\010MacEvent\022\023\n\013locatio" +
      "n_id\030\001 \001(\005\022\023\n\013mac_address\030\002 \001(\014\022\022\n\nstart" +
      "_usec\030\003 \001(\003\022\020\n\010end_usec\030\004 \001(\003\0227\n\nevent_t" +
      "ype\030\005 \001(\0162#.helloagain.data.MacEvent.Eve" +
      "ntType\022\022\n\treturning\030\350\007 \001(\010\022\025\n\014visit_numb" +
      "er\030\351\007 \001(\005\022\024\n\013item_number\030\352\007 \001(\005\"1\n\tEvent" +
      "Type\022\013\n\007UNKNOWN\020\000\022\014\n\010PRESENCE\020\001\022\t\n\005VISIT" +
      "\020\002\"\212\001\n\016DeviceLocation\022\023\n\013device_name\030\001 \001" +
      "(\t\022\021\n\tdevice_id\030\002 \001(\003\022\025\n\rlocation_name\030\003" +
      " \001(\t\022\023\n\013location_id\030\004 \001(\005\022\022\n\nstart_usec\030",
      "\005 \001(\003\022\020\n\010end_usec\030\006 \001(\003\"7\n\013LocationMac\022\023" +
      "\n\013location_id\030\001 \001(\005\022\023\n\013mac_address\030\002 \001(\014" +
      "\"8\n\tDeviceDay\022\023\n\013device_name\030\001 \001(\014\022\026\n\016ti" +
      "mestamp_usec\030\002 \001(\003B\032\n\022eu.pawelsz.apache.beam.io.protoio" +
      "Z\004data"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_helloagain_data_RawItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_helloagain_data_RawItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_helloagain_data_RawItem_descriptor,
              new java.lang.String[] { "TimestampUsec", "DeviceName", "MacAddress", "SignalStrength", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
